name: Build

on:
  pull_request:
  push:
    branches-ignore:
      - gh-pages

jobs: 
  build:
    container:
      image: ghcr.io/armmbed/mbed-os-env:latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Work around CVE-2022-24765
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Compile movement firmware
        run: make
        working-directory: '.'
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: firmware.uf2
          path: build/firmware.uf2
